name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Download release
        run: gh release download $(git describe --tags --abbrev=0) --skip-existing
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_KEY }}

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: fyrstelin
        
      - name: Publish to nuget
        run: dotnet nuget push *.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
