name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Download release
        run: gh release download $(git describe --tags --abbrev=0) --skip-existing
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_KEY }}
      - name: Publish to nuget
        run: dotnet nuget push *.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      - name: Unlist alpha on nuget
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          if [[ "$VERSION" == *"alpha"* ]]; then
            for pkg in $(find . -name '*.nupkg'); do
              PACKAGE_ID=$(basename "$pkg" | sed -E 's/(.*)\.[0-9]+\.[0-9]+\.[0-9]+.*\.nupkg/\1/')
              echo "Unlisting package: $PACKAGE_ID, Version: $VERSION"

              dotnet nuget delete $PACKAGE_ID $VERSION -k $NUGET_KEY --non-interactive -s https://api.nuget.org/v3/index.json
            done
          fi
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}